# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Upload to GitHub
          command: npm run test
            if [ $? -eq 0 ]; then
              # Tests passed, upload to GitHub
              git config user.name "CircleCI"
              git config user.email "<muhammad.muneeb@qenta.com>"
              git add .
              git commit -m "Passed tests [skip ci]"
              git push origin HEAD:master
            else
              # Tests failed, exit with a non-zero code
              exit 1
            fi
       - store_test_results:
           path: /tests_output
workflows:
  e2e-test:
    jobs:
      - test